### ISSUE TITLE
RDFizer: marc conversion doesn't generate triples in the user interface

### ISSUE THREAD

**Issue by cgareta** [ALIADA/aliada-tool#77]
After cleaning the graphs for marc triples, the conversion of marc xml files doesn't show any triple in the Check RDF screen. Could you perform a test using your marcxml files just to verify if the RDFizer is processing marc files? 
Please, give the feedback to @xmolero 
Best, 
Cristina

**Comment by xmolero** [comment]
The problem is that we perfom a test with a marcxml file and we don´t show any triple in the user interface. But in the SPARQL server (Virtuoso), if we make a request for triples, the server shows triples correctly.

**Comment by agazzarini** [comment]
@xmolero as far as I remember the user interface, if you mean the ALIADA user interface, doesn't show the results of the conversion. However, even if it is so, I guess it does that by querying the triple store. So, if you say that the expected triples are on Virtuoso (executing a SPARQL query) I would say that the problem is in the interface, not in RDFizer.

Make sense?

**Comment by xmolero** [comment]
@agazzarini how you perform the following operations: the records and the triples throughput?

**Comment by agazzarini** [comment]
@xmolero those are simple operations like  (elapsed rec1 + elapsed rec2 + ...) / total records number . The same for triples

**Comment by xmolero** [comment]
OK, thank you
